### ISSUE TITLE
Instructions

### ISSUE THREAD

**Issue by exiom-xyz** [MorpheusXAUT/eveslackkills#1]
Hi there,

Thanks for releasing such a good tool, but can you be so kind as to releasing a set of small instructions of how to put this to use?

Best Regards
Jackson

**Comment by MorpheusXAUT** [comment]
Hey,

I can look into throwing together some quick instructions tomorrow since it's too late today already.

Basically, you only need to set up the Go runtime/compile the app and set up the required database with the provided script in database/mysql/eveslackkills_create.sql.
The app also needs the "invTypes" and "mapSolarSystems" tables from the EVE Online static data export (to be found [e.g. here](https://www.fuzzwork.co.uk/dump/mysql-latest.tar.bz2)). Since those two tables are huge, they are not bundled with the app.

Lastly, place a "config.cfg" file within the same folder as the executable, using a JSON format like this:

`{
    "DatabaseType": 1,
    "DatabaseHost": "HOST:PORT",
    "DatabaseSchema": "DATABASE",
    "DatabaseUser": "USER",
    "DatabasePassword": "PASSWORD",
    "DebugLevel": 1,
    "SlackWebhookURL": "SLACK_WEB_HOOK"
}`

**Comment by MorpheusXAUT** [comment]
Instructions have been added to the README.md file.

Hope that helps!
